apiVersion: app.yj.io/v1beta1
kind: MyApp
metadata:
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: myapp-sample
spec:
  size: 3
  image: docker.io/library/nginx:1.7.9
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002

